[project]
name = "fastapiproject"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.13"
dependencies = [
    "fastapi>=0.115.8",
    "pydantic>=2.10.6",
    "sqlalchemy>=2.0.38",
    "uvicorn>=0.34.0",
    "aiosqlite==0.21.0"
]
